### ISSUE TITLE
Bunch of mac problems

### ISSUE THREAD

**Issue by vvLux** [SevenTV/Extension#383]
when having 7tv installed the ability to see any badges (subscriber badge, moderator, VIP, prime etc) are not shown, also the tab auto complete emote not working and many more other minor issues

**Comment by AnatoleAM** [comment]
All issues mentioned were fixed in 3.0.1. (tab-complete was not a native issue but rather a conflict with other extensions) 

If you want these fixes now use the nightly build. [[chromium]](https://chrome.google.com/webstore/detail/7tv-nightly/fphegifdehlodcepfkgofelcenelpedj?referrer=7tv.app) [[firefox]](https://addons.mozilla.org/en-US/firefox/addon/7tv-nightly/)
