### ISSUE TITLE
[Request] Integrate the pronouns API

### ISSUE THREAD

**Issue by soycan-sim** [SevenTV/Extension#385]
The 3.0 update broke compatibility with the [Pronouns extension](https://pronouns.alejo.io/) on twitch and the extension itself seems to no longer be maintained [Alejo47/chat_pronouns_browser_extension](https://github.com/Alejo47/chat_pronouns_browser_extension). I'd be interested in adding support for the original API as a pure client-side solution. I'll fork and start working on it as soon as I have some time.

Open questions:
- Should it be opt-in or opt-out?
- Could this functionality be implemented natively? This would require changes to the website, API and persistent storage as well. If so, I'd be willing to help implement it.
- @alejo47 : Any objections against using the API in 7tv?

**Comment by soycan-sim** [comment]
The original API is:

1. Used to query a user, the pronoun id is used to lookup the readable pronoun from the 2nd API.
```
GET https://pronouns.alejo.io/api/users/{username}
[{"id":"...", "login":"...", "pronoun_id":"..."}]
```

2. Returns a list of readable pronouns.
```
GET https://pronouns.alejo.io/api/pronouns
[{"name":"...", "display":"..."}, ...]
```

**Comment by AnatoleAM** [comment]
This is probably something that would work better with the [EventAPI](https://github.com/seventv/eventapi) and could tie onto our dynamic user presence state / cosmetics system. 

As-is, making an HTTP request for every new username in chat, would be quite inefficient.

**Comment by Irithind** [comment]
Bumping the post. We really need that integration.

**Comment by JDThralls** [comment]
Not hiding the already-existing extension would help without any further work needed to integrate calls to the API into 7tv itself.

One of my main issues with this is that 7tv hides the already-happening use of the API by hiding the badges that the original extension adds to twitch's chat.

Removing the freedom for people to use other extensions (especially those that do not compete or interfere with 7tv's business model) is just outright bad software, UX and process design.

**Comment by AnatoleAM** [comment]
@JDThralls,

That's a misconception of how extensions work. There is generally, no such thing as simply just "not hiding". Nothing is being removed on purpose, but as it happens multiple extensions that affect the same area of one given website might not behave properly.

Similar extensions either have an add-on system or perhaps employ a less aggressive "patching" mechanism (which wouldn't allow for the kinds of performance and UX improvements 7TV provides).

This is an open project and anybody is totally free to submit a pull request adding support for pronouns. There are also plans for a plugin system in the future, which would provide an extensive API to add custom features to chat and beyond.

**Comment by JDThralls** [comment]
> That's a misconception of how extensions work. There is generally, no such thing as simply just "not hiding".

I do not see how it would be a misconception of how extensions work. Software either does or does not interfere with other software, be it extensions or not. You did not interfere previously, now you do. That seems more like a bug to me than a misconception on my end. Extensions are supposed to be built such that they do not interfere with other extensions or the core systems as that is usually how extensions should work. They are supposed to **extend**, not **reduce** the set of features provided. Any interference with another system need to be justified, not simply forced because it is easier for the developers.

> Nothing is being removed on purpose, but as it happens multiple extensions that affect the same area of one given website might not behave properly.

You are overriding the entire chat on purpose, you are quite literally hiding everything that interacts with the original chat. That is not regular behaviour, that is on your end. If you are overriding everything and not considering adding support so that other extensions can keep working, that is definitely not an open ecosystem, that is locking down people's choice of extensions.

> Similar extensions either have an add-on system or perhaps employ a less aggressive "patching" mechanism (which wouldn't allow for the kinds of performance and UX improvements 7TV provides).

Before the extension started overriding the entire chat, there were no such issues, the extensions worked together perfectly (and had much better performance on most devices). As such, it seems like a conscious decision made on your end, whether it actually is or not, the actions definitely speak that language.

If you break the user experience without asking the user, that is bad UX design.

> There are also plans for a plugin system in the future, which would provide an extensive API to add custom features to chat and beyond.

As long as there is no compatibility with other extensions and no extension system or API for this extension, people should have a choice whether or not they want all their other extensions hidden or not. (It should also still exist, even if there is an API/Extension ecosystem.)

**Comment by AnatoleAM** [comment]
> Software either does or does not interfere with other software, be it extensions or not. It did not interfere previously, now it does. 

Previously, the extension did very little and would completely disable itself if one of the other more mature chat extension was installed. That however had to change with a growing featureset, and it did. The only difference between then and now is which extension takes precedence. There was always, only a single extension rendering chat.

There is no bug, this is absolutely on purpose. And it does extend the featureset, which its own features.

> You are overriding the entire chat on purpose

Yes. So does FrankerFaceZ, as an example.

> If you are overriding everything and not considering adding support so that other extensions can keep working, that is definitely not an open ecosystem, that is locking down people's choice of extensions.

You have control over your own browser. If you're unhappy with the features we provide, and do not want to contribute to the project, then it's completely up to you not to use the extension.

> Before the extension started overriding the entire chat, there were no such issues, the extensions worked together perfectly

None of the major extensions have ever worked together without issue. It was always the case that one of them let another handle everything. It simply changed with version v3.0, where we opted to take precedence instead.

---

Again, you hold a misunderstanding of the kind of environment these extensions work in. It's a fight for control, there is no harmony. One of them will override the others, this is inevitable, you cannot do otherwise. The level of compatibility depends on how much developers can work with one another. **I have never been contacted by the developers of the pronouns extension**.

**Comment by JDThralls** [comment]
> Previously, the extension did very little and would completely disable itself if one of the other more mature chat extension was installed. That however had to change with a growing featureset, and it did. The only difference between then and now is which extension takes precedence. There was always, only a single extension rendering chat.
> [...]
> Again, you hold a misunderstanding of the kind of environment these extensions work in. It's a fight for control, there is no harmony. One of them will override the others, this is inevitable, you cannot do otherwise. The level of compatibility depends on how much developers can work with one another.

There is a fight for control between the 7tv extension and other extensions that do use that approach, yes, however, we are talking about non-invasive ones that 7tv is still hiding and you are justifying it with the fight for control with extensions unrelated to the issue.

Alejo's extension does not use that approach, it injects a badge into the regular twitch chat and it happens to integrate with other render-overrides because they, unlike 7tv, respect those extensions' approach.

> Yes. So does FrankerFaceZ, as an example.
> [...]
> **I have never been contacted by the developers of the pronouns extension.**

Obviously, yes, which does not mean that you can just break the user experience. It is not about them contacting you, you should make sure you respect approaches like that. if something adds elements on top of an already-rendered chat by hooking into that, it should be able to do the same with your render engine too, seamlessly, otherwise, you are removing features, not extending the original experience, which is a UX flaw as well, as it breaks compatibility. Alejo likely never contacted the other extension creators either, but their extensions did work with it.

> You have control over your own browser. If you're unhappy with the features we provide, and do not want to contribute to the project, then it's completely up to you not to use the extension.

So, you are saying this is an open project, meaning it should also be open to criticism, but you are also saying that you do not want this criticism here and that people who have issues with the behaviour should just uninstall the extension? That is not a fix, that is childish.

> None of the major extensions have ever worked together without issue. It was always the case that one of them let another handle everything. It simply changed with version v3.0, where we opted to take precedence instead.

Again, we weren't talking about FFZ or BTTV, but all the other extensions that hooked into the basic twitch chat and that all other renderers did honour by porting those hooks and even all the changes they did to the original chat over to their renderers, which 7tv currently does not do, hiding all other extensions, breaking UX.

**Comment by AnatoleAM** [comment]
> non-invasive ones that 7tv is still hiding and you are justifying it with the fight for control with extensions unrelated to the issue.

I'm pointing out the fact that these unrelated, smaller extensions still would have had to make special implementations to work with either of the other major providers. The developer(s) of the pronouns extension have stated before they have no plans to integrate, despite the fact we'd likely have made it possible if contacted.

> Obviously, yes, which does not mean that you can just break the user experience. It is not about them contacting you, you should make sure you respect approaches like that

Unfortunately, there are many different things that a given user wants. There is no way to cater to 100% of it. Our goal is to provide a best-in-class experience for the average user, less-so cater to the smaller percentage of power users insofar. I believe the explosive growth of our extension in both users and rating since the release of v3.0 (from 3.9 to 4.5 :star:) speaks for itself.

We still plan to provide support for many things, but there are certain priorities our team have, so unless an external contribution is made, it would take time.

> So, you are saying this is an open project, meaning it should also be open to criticism, but you are also saying that you do not want this criticism here

Well, we're providing an experience, and if it doesn't suit you then you can either request a change, make the change yourself, or go somewhere else. That doesn't mean your criticism isn't being considered, it's just that I don't have a solution for you and you don't seem to have one either.

> all the other extensions that hook(ed) into the basic twitch chat and that all other renderers did honour by porting those hooks and even all the changes they did to the original chat over to their renderers

Speaking from experience, this is mostly untrue. It was a gigantic chore to work around these other chat-modifying extensions before v3, where random re-renders and eventual sudden freezes due to clashing hooks eventually led to us  waving the white flag and self-disabling upon detection.

If anything, this provides the cleanest possible environment for a future extensive plugins API. Which is very much planned, and would allow anyone to customize everything.

**Comment by JDThralls** [comment]
> Well, we're providing an experience, and if it doesn't suit you then you can either request a change, make the change yourself, or go somewhere else.

Yes, but the experience you provided before differs from the experience now, which is what I am referring to.

> That doesn't mean your criticism isn't being considered, it's just that I don't have a solution for you and you don't seem to have one either.

What you are saying does not sound like it is being considered, it sounds like trying to find an excuse to not do it. It might be a misunderstanding, but nonetheless that is how it is received.

I proposed a solution: Give the user an option.

This can be done by providing a switch in the user configuration to the old behaviour, so it works as it used to - for those concerned with it. I could create a new enhancement request for it, as it might impact more than this one extension/enhancement.

I currently don't have the time to make a patch for the project, sadly, otherwise I would have months ago. If I get around to it, I'll make a patch for it.

> Speaking from experience, this is mostly untrue. It was a gigantic chore to work around these other chat-modifying extensions before v3, where random re-renders and eventual sudden freezes due to clashing hooks eventually led to us waving the white flag and self-disabling upon detection.

Again, we are not talking about FFZ/BTTV and 7tv co-operating, you did way more than just replacing text with an image tag or appending a `div`/`span` tag to the badge list, which extremely complicates interoperability. The situation doesn't get any better with your extension being a direct competitor to FFZ and BTTV, which means there was a motive for them to make it harder for you.

> If anything, this provides the cleanest possible environment for a future extensive plugins API. Which is very much planned, and would allow anyone to customize everything.

Yes, it does (at least on your end, which is kind of fine if you create an open add-on ecosystem). but this issue has been open for almost 5 months now, with no end in sight yet (at least no clear sign when we will be there). So, we currently have a broken experience and no alternative.

**Comment by JDThralls** [comment]
Adding pronouns to the 7tv user profile would probably fix this issue (specifically) more cleanly and make the no-longer maintained extension, that you say is so complicated to integrate, obsolete for all 7tv users. The request to get the pronouns could be omitted if the pronouns would be returned with the rest of the profile information, such as the paint.

However, it can also be fixed by adding a few classes to some elements and just letting the extension do its usual DOM injection:

For making the original extension work with 7tv, all that is required, is to make sure that

- The message element added to the message container would need to have the class `chat-line__message` (in order to not skip processing) (quickly glancing at the current markup, the element in question to add this to seems to be the `.seventv-message`).
- The username's element would need to match the query selector `span.chat-author__display-name` (the username is read using `.textContent` from that element, so adding this class to the username wrapper would suffice).
- The badge list where it can inject the badge would have to match the query selector `.chat-line__username-container > span:not(.chat-line__username)` (quickly glancing at the current markup, the element in question to add this to seems to be the `.seventv-chat-user`).

If these are the case, it will just append them using regular DOM manipulation, no hooks required.

Both the user element and the badge list element query selectors are run from the message element's context.

Should also add a padding reset for the class `chat-line__message`, as twitch's native styling has a `0.5rem 2rem` padding around it and that would break slider positioning.

If I get around to it, I'll look into where to inject the classes into the process of building the message elements and what CSS overrides/resets are required in the 7tv extension for this approach to work, I am just quite busy, so it might take a while until I find it in the source I haven't read yet (the extension source).

**Comment by Melonify** [comment]
@soycan-sim This thread was closed as it got quite off-topic, if you're still interested in a possible addition to the 7TV extension, I suggest reopening a new issue. 

However, I do think that an auxiliary feature like this which integrates into a third party API is probably better off suited for when the addon's system is implemented later down the line.
