### ISSUE TITLE
[Twitch] Animated avatars not working

### ISSUE THREAD

**Issue by FourLineCode** [SevenTV/Extension#393]
Version 3.0.1
OS: MacOS ventura (M2)
Browser: Chrome 111.x

Channels in view - cyr/nymn
<img width="994" alt="image" src="https://user-images.githubusercontent.com/56719270/228036060-0d554d9e-c927-4636-a261-6783df0c30ae.png">

**Comment by FourLineCode** [comment]
Seems to be working now after restart. But it just takes 8-10 seconds before animated avatar is loaded.

Closing the issue for now.

**Comment by Batyodie** [comment]
@FourLineCode I think the long loading is due to the fact that the twitch web is loaded first, and then the extension logic is loaded. For the extension to work correctly, you must wait for the page to fully load, only then make any changes to it.

In theory, you can optimize the work and speed up the appearance of an animated avatar. In any case, happy to help. :+1:
