### ISSUE TITLE
[Resolved] BetterTTV channel emotes not working

### ISSUE THREAD

**Issue by RealLarwood** [SevenTV/Extension#447]
Ever since the 3.0 update BTTV channel emotes have not been working.

If I have the BTTV extension enabled then BTTV emotes will auto-complete and appear on the carousel, but in chat I only see the words and none of the emotes. BTTV global emotes and all other emotes work fine.

If I disable the BTTV extension then BTTV channel emotes do not even appear on auto-complete.

Firefox 111.0.1 on Win 10.

**Comment by AnatoleAM** [comment]
Hey,

this is due to BTTV blocking our extension from seeing their emotes (out of pure pettiness.)

This is worked around via #445 #446 and fixed with [v3.0.3](https://github.com/SevenTV/Extension/releases/tag/v3.0.3)

In the meantime, you can use the nightly version of the extension. Also consider telling your favorite streamers about migrating to 7TV, we've got a ton of emote slots for free :smile:

**Comment by gruxor** [comment]
I know that this is closed and more or less handled, but given that there's [contention from BTTV that this is occurring](https://github.com/night/betterttv/issues/6060) and instead they're claiming that it's a result of the 7tv extension's chat renderer, can someone provide some evidence that there's intentional blocking going on? A commit or file change, etc.?

The 7tv commits linked above also don't seem to be a bypass of any sort to circumvent anything as far as I can tell, other than not using JSON headers unnecessarily during certain fetch requests, so I'm a bit confused. Unless those headers are what's being used to block the data, I guess, during that request. Would appreciate some details there for those (like myself) less familiar with the situation.

I lean toward 7tv in pretty much every regard, but I'd rather not believe one story over another without good reason.

**Comment by AnatoleAM** [comment]
@gruxor, 

The header was indeed being used as a form of fingerprinting. It also had the side effect of triggering pre-flight requests, which may have looked like increases in request rate to web servers. However, pre-flight / cors (OPTIONS) requests are inert and do no damage. 

In essence, it is correct to call the presence of a content type header a misconfiguration, as it causes the browser to issue CORS checks.

That being said, knowing this wasn't damaging to an API, creates no additional cost and is easily filtered from logs, it's very clear that this was used as a means and excuse to break our implementation. If nightdev had simply told us, "hey, I think your extension is doing unnecessary cors checks, would you mind looking into it?", we would've fixed it quietly, but by keeping this blockage while knowing updating a chrome extension takes time essentially forced our hand into issuing a statement and providing an alternative, lest we receive blame for something outside of our control.

---

As for the chat renderer complaints, it's irrelevant to this issue. It must be understood that extensions are required to take over chat rendering in order to work. FrankerFaceZ does this too, in fact the BetterTTV extension has almost no effect when FFZ is enabled, similar to our v2 extension. The new extension now takes precedence over ffz chat rendering, which is the only true difference in play.

**Comment by AnatoleAM** [comment]
It should be noted that the issue on nights end is locked, which should be a red flag to anyone reading. It's an obvious mis-characterization and defamatory statement, yet he is not allowing any discussion within.
