### ISSUE TITLE
[BUG] Firefox nightly release is also out of date

### ISSUE THREAD

**Issue by QuaidMars** [SevenTV/Extension#543]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### This issue exists in the latest nightly version

- [X] I am using the latest nightly version

### What browsers are you seeing the problem on?

Firefox

### Current Behavior

When I go to https://addons.mozilla.org/en-US/firefox/addon/7tv-nightly/?referrer=7tv.app (from the 7tv.app homepage)
I'm presented with the nightly extension which is version 3.0.0.12200, updated on Feb 20.

### Expected Behavior

Expect to see 3.0.6.1000, which is the version that https://7tv.app/ purports to be the latest nightly.

### Steps To Reproduce

Go to https://7tv.app/ in firefox stable.
Click on the button to navigate to the nightly release.

I didn't see any tweets or issues about this either.
I really don't want to have to install firefox nightly in order to install an unverified extension.

**Comment by AnatoleAM** [comment]
Mozilla deleted most of the versions of nightly and automatically downgraded everyone, god knows why. I've removed it from their addons store, will put up the self-distributed version on the site instead.

You could also use a chromium-based browser, which work much better and typically aren't ran by incompetent companies like mozilla.

**Comment by AnatoleAM** [comment]
I have no stance on FF, I'm just telling you what mozilla, the company which controls firefox, did. There is no working around this level of incompetence on their end.

**Comment by gagbo** [comment]
Hello, is there a way to follow the resolution of this issue on FF side? A bug tracker or something on firefox or on a reviewboard for extensions? It really seems weird that they would delete versions of an extension without warning/explanations/post-mortems/anything

**Comment by Totto16** [comment]
The nightly version is now completely gone on the FF addons store. 
And all I see is "gross mishandling of Mozillas Site". No details, nothing is explained. What is the exact reason Mozilla "banned"  / removed both addons. I trust Mozilla more than you. So if you don't provide some proofs that you did nothing wrong, I'll assume that *you* violated some Privacy or ToS of Mozilla and it's your fault not Mozillas. Mozilla is known to go for Privacy, so if youre addon isn't on there store it's really looking bad for you. :thinking:

**Comment by AnatoleAM** [comment]
@Totto16,

it's not actually gone I just [renamed it](https://addons.mozilla.org/en-US/firefox/addon/7tv-old/) since they've reverted it to a super old version.

Since you're on our github repository which contains 100% of the code published to either CWS or AMO (you can even view the build logs and subsequent publish action, which is fully automated so no post-processing can occur), you can check for yourself that there is nothing wrong with the 7TV Extension.

We're not sure why mozilla is doing this, but they've actually reviewed a completely different extension, flagged ours for it, then refused any appeal. Nightly was also recently randomly removed, supposedly because the source code was not attached, despite the fact it was. It then took 2 weeks for them to re-review, which they've just denied a few days ago because it seems that despite clear instructions, their reviewers aren't able to build the extension. (You can see the README for yourself as for how easy it actually is to compile).

Also, it's worth noting there is actually no such thing as a "privacy browser". In fact, just Google Chrome with uBlock Origin installed is going to be significantly more private than vanilla firefox. Furthermore, Mozilla is a company substantially or wholly funded by Google, which really doesn't build a strong case for them being your privacy savior.

**Comment by Totto16** [comment]
@AnatoleAM thanks for clarification, as I said, you can't find reliable information anywhere. But Google Chrome is more Spyware then FF. But lets not focus on that conversation. I managed to build teh extension, but FF (also chrome) doesn't allow extensions, that are not signed to be installed for more than a session, so it's not an option to reinstall the extension every time I reopen the browser :sweat: 

Anyway, thanks for clarification, and if Mozillas reviewers are that :hankey: it's bad. But as far as I heard from others it's not clear to the users, so maybe write a disclaimer somehwere, stating clearly, that it's not your fault
:smile:

**Comment by gagbo** [comment]
> but I haven't figured out auto-updating yet.

In case you missed it, [FF docs say](https://extensionworkshop.com/documentation/publish/self-distribution/)

> To enable Firefox to automatically update self-distributed add-ons, you need to include the URL where Firefox can find updates in the add-on manifest's [update_url](https://developer.mozilla.org/docs/Mozilla/Add-ons/Updates) key.

I guess some route (serving the manifest with URLs pointing to github release artifacts) could be added to the main site of 7tv, but that's a bunch of extra work for sure

**Comment by Azyrion** [comment]
As gagbo said: I tried to reinstall it from here only for ff to block it cause "damaged extension"

**Comment by Wanesty** [comment]
https://github.com/SevenTV/Extension/blob/6ebb14d937b6d2f518dc2691f3a3cb42d51f49b4/.github/workflows/ci.yaml#L41

the .xci somehow build with the chrome id :
"ammjkodgmmoknidbanneddgankgfejfh"

instead of the mozilla id : 
"moz-addon-prod@7tv.app"

i guess it's comming from your workflow configuration and you might be aware of it but that is what is causing this : 
![image](https://user-images.githubusercontent.com/98633588/236765241-ff377cbb-ac18-495d-83f6-29b9e6a48df7.png)

still no signature so not completely fixed but i believe it's part of the issue

**Comment by ShowMeBillyJo** [comment]
> https://github.com/SevenTV/Extension/blob/6ebb14d937b6d2f518dc2691f3a3cb42d51f49b4/.github/workflows/ci.yaml#L41
> 
> the .xci somehow build with the chrome id : "ammjkodgmmoknidbanneddgankgfejfh" and "fphegifdehlodcepfkgofelcenelpedj" ![image](https://user-images.githubusercontent.com/98633588/236765527-27ba347d-455c-4671-b07d-9277af744bfb.png)
> 
> instead of the mozilla id : "[moz-addon-prod@7tv.app](mailto:moz-addon-prod@7tv.app)" and "[moz-addon@7tv.app](mailto:moz-addon@7tv.app)"
> 
> i guess it's coming from your workflow configuration and you might be aware of it but that is what is causing this : ![image](https://user-images.githubusercontent.com/98633588/236765241-ff377cbb-ac18-495d-83f6-29b9e6a48df7.png)
> 
> changing it makes me able to install it in debug mod but still no signature so not completely fixed
> 
> edit : i just realize i'm saying exactly what gagbo said 💀 edit 2 : so yea that seems to fix it but as lead dev and maintainer you shall be the one signing it edit 3 : "version_name":"3.0.6" in the manifest causes a warn, and i see no other of my installed extensions declaring this value

If IDs and such are wrong, that might be why Mozilla keep rejecting it.

At any rate, this is annoying because the 7tv icon on Twitch and YT keeps flashing with a bright green ping that doesn't/can't do anything.

**Comment by AnatoleAM** [comment]
Tracked in #573

**Comment by AnatoleAM** [comment]
[Nightly Release](https://github.com/SevenTV/Extension/releases/tag/nightly-release) is now signed per #573 

Website links will be updated when v3.0.7 releases

**Comment by gagbo** [comment]
Can confirm the latest `7tv-webextension-ext-signed.xpi` installed fine for me 

![image](https://github.com/SevenTV/Extension/assets/10496163/9b7154f9-9fff-4d29-a701-e8fc73ba9863)

Thanks a lot!!

**Comment by Wanesty** [comment]
the signed **Nightly Release** : https://github.com/SevenTV/Extension/actions/runs/4927350886
   _7tv-webextension-ext-signed.xpi_

got overwritten by : https://github.com/SevenTV/Extension/actions/runs/4931091117/jobs/8812784677
   _7tv-webextension-ext.xpi_

---
in the meantime : the file can be found [here](https://github.com/SevenTV/Extension/actions/runs/4927350886) download the "_installable_" artifact at the bottom, unzip it and install the file named "_ext-signed.xpi_"
